# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05b_inference_birds.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
import matplotlib.pyplot as plt
from fastcore.all import *

from .torch_utils import Normalizer
from .data_birds import BertTokenizer
from .model import Birds_Export

# Internal Cell
normalizer = Normalizer()
tokenizer = BertTokenizer()

# Internal Cell
def decode_img(img):
    "img: (bs, 3, _, _), returns: (bs, _, _, 3)"
    imgs = normalizer.decode(img).permute(0, 2, 3, 1).cpu()
    return imgs

# Internal Cell
def get_attn_w(model):
    "return: (bs, seq_len, w, h)"
    attn_w = model.g_net.gs_attn[-1].conv[0].attn_w # (bs, h, w, seq_len)
    return attn_w.permute(0, 3, 1, 2) # (bs, seq_len, h, w)

# Cell
@patch
@torch.no_grad()
def predict(self: Birds_Export, cap):
    ''' cap: 'this bird is red with white and has a very short beak.'
        returns: img: (256, 256, 3), attn_w: (60, 128, 128) '''
    cap, cap_len = tokenizer.encode(re.sub(r'[^\w\s]','',cap).lower())
    cap = torch.tensor([cap])
    cap_len = torch.tensor([cap_len])
    self.eval()
    img = self.forward(cap, cap_len)
#     img = self.small_forward(cap, cap_len)
    img = decode_img(img)
    attn_w = get_attn_w(self)
    return img[0], attn_w[0]

# Internal Cell
def show_pred(img, cap):
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(4, 4))
    ax.imshow(img)
    ax.set_title(cap)

# Internal Cell
def show_pred_withattn(img, attn_w, cap):
    ''' img: (256, 256, 3), attn_w: (60, 128, 128), cap: 'this is a white bird with a grey cheek patch and a black eyebrow.' '''
    cap, cap_len = tokenizer.encode(re.sub(r'[^\w\s]','',cap).lower())

    ncols=4
    nrows=math.ceil((cap_len+1)/ncols)
    figsize = (ncols*4, nrows*4)
    fig, ax = plt.subplots(nrows=nrows, ncols=ncols, figsize=figsize)
    axs = ax.flatten()
    axs[0].imshow(img)
    for i in range(cap_len):
        axs[i+1].set_title(tokenizer.decode([cap[i]]))
        axs[i+1].imshow(attn_w[i])

# Cell
@patch
def pred_and_show(self: Birds_Export, cap, with_attn=False):
    "cap: 'a bird with a grey body and yellow feathers on its belly with a longish beak' "
    img, attn_w = self.predict(cap)
    show_pred_withattn(img, attn_w, cap) if with_attn else show_pred(img, cap)