# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05a_inference_anime_heads.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
import matplotlib.pyplot as plt
from fastcore.all import *

from .torch_utils import Normalizer
from .data_anime_heads import Tokenizer
from .model import Anime_Export

# Internal Cell
normalizer = Normalizer()
tokenizer = Tokenizer()

# Internal Cell
def decode_img(img):
    "img: (bs, 3, _, _), returns: (bs, _, _, 3)"
    imgs = normalizer.decode(img).permute(0, 2, 3, 1).cpu()
    return imgs

# Internal Cell
def get_attn_w(model):
    "return: (bs, seq_len, w, h)"
    attn_w = model.g_net.gs_attn[-1].conv[0].attn_w # (bs, h, w, seq_len)
    return attn_w.permute(0, 3, 1, 2) # (bs, seq_len, h, w)

# Cell
@patch
@torch.no_grad()
def predict(self: Anime_Export, cap):
    ''' cap: 'white hair yellow eyes'
        returns: img: (64, 64, 3), attn_w: (2, 64, 64) '''
    cap, cap_len = tokenizer.encode(cap)
    cap = torch.tensor([cap])
    cap_len = torch.tensor([cap_len])

    self.eval()
    img = self.forward(cap, cap_len)
#     img = self.small_forward(cap, cap_len)

    img = decode_img(img)
    attn_w = get_attn_w(self)
    return img[0], attn_w[0]

# Internal Cell
def show_pred(img, cap):
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(2, 2))
    ax.imshow(img)
    ax.set_title(cap)

# Internal Cell
def show_pred_withattn(img, attn_w, cap):
    ''' img: (64, 64, 3), attn_w: (2, 64, 64), cap: 'white hair yellow eyes' '''
    tags = [' '.join(cap.split()[:2]), ' '.join(cap.split()[2:])]

    fig, ax = plt.subplots(nrows=1, ncols=3, figsize=(6, 2))
    axs = ax.flatten()
    axs[0].imshow(img)
    axs[1].set_title(tags[0])
    axs[1].imshow(attn_w[0])
    axs[2].set_title(tags[1])
    axs[2].imshow(attn_w[1])

# Cell
@patch
def pred_and_show(self: Anime_Export, cap, with_attn=False):
    "cap: 'white hair yellow eyes' "
    img, attn_w = self.predict(cap)
    show_pred_withattn(img, attn_w, cap) if with_attn else show_pred(img, cap)